FROM opensuse:42.1

# RUN zypper update
# RUN zypper --no-refresh --non-interactive install -l\
# 	gcc-c++ \
# 	python \
# 	python-devel \ 
# 	git \
# 	cmake \
# 	inkscape \
# 	openexr-devel \
# 	qt-devel \
# 	postgresql-devel \
# 	make \
# 	rpm-build

# COPY . /opt/cgru
# WORKDIR /opt/cgru

# RUN cd utilities/exrjoin && ./build.sh
# RUN cd afanasy/src/project.cmake && ./build.sh
# RUN cd utilities/release && ./make_linuxpackages.sh --skipcheck